sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t meuhmeuh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true meuhmeuh/docker-react npm run test
